FROM jboss/wildfly
ADD standalone.xml /opt/wildfly/standalone/configuration/
ADD mgmt-users.properties /opt/wildfly/standalone/configuration/
ADD mgmt-groups.properties /opt/wildfly/standalone/configuration/
